import type { Product } from "@/lib/types"

// Central seed data for the SQLite database.
export const seedProducts: Product[] = [
    {
        id: 1,
        name: "iPhone 14",
        price: 89900,
        imageUrl: "/iphone-14.png",
        category: "electronics",
        description: "Apple smartphone 128GB",
        retailer: "Tech Store Tirana",
        distance: 2.5,
        originalPrice: 95000,
        inStock: true,
        location: "Tirana",
        market: "Tech Store Tirana",
        marketSlug: "tech-store-tirana",
    },
    {
        id: 2,
        name: "Samsung Galaxy S23",
        price: 79900,
        imageUrl: "/samsung-galaxy-s23.png",
        category: "electronics",
        description: "Samsung smartphone 256GB",
        retailer: "Mobile World",
        distance: 3.8,
        originalPrice: 85000,
        inStock: true,
        location: "Tirana",
        market: "Mobile World",
        marketSlug: "mobile-world",
    },
    {
        id: 3,
        name: "MacBook Air M2",
        price: 119900,
        imageUrl: "/macbook-air-m2.png",
        category: "computers",
        description: "Apple laptop with the M2 chip",
        retailer: "Computer Center",
        distance: 1.2,
        inStock: false,
        location: "Tirana",
        market: "Computer Center",
        marketSlug: "computer-center",
    },
    {
        id: 4,
        name: "Sony WH-1000XM5",
        price: 35900,
        imageUrl: "/wireless-headphones.png",
        category: "audio",
        description: "Noise-cancelling headphones",
        retailer: "Audio Pro",
        distance: 4.5,
        originalPrice: 39900,
        inStock: true,
        location: "Durres",
        market: "Audio Pro",
        marketSlug: "audio-pro",
    },
    {
        id: 5,
        name: "iPad Air",
        price: 59900,
        imageUrl: "/ipad-air.png",
        category: "tablets",
        description: "Apple tablet 64GB",
        retailer: "iStore Albania",
        distance: 2.1,
        inStock: true,
        location: "Tirana",
        market: "iStore Albania",
        marketSlug: "istore-albania",
    },
    {
        id: 6,
        name: "Dell XPS 15",
        price: 149900,
        imageUrl: "/dell-laptop.png",
        category: "computers",
        description: "Professional laptop i7",
        retailer: "Tech Hub",
        distance: 5.3,
        originalPrice: 159900,
        inStock: true,
        location: "Shkoder",
        market: "Tech Hub",
        marketSlug: "tech-hub",
    },
    {
        id: 7,
        name: "Komiteti Special",
        price: 700,
        imageUrl: "/images/Komiteti.jpeg",
        category: "bars",
        description: "Traditional Albanian raki and local drinks",
        retailer: "Komiteti",
        distance: 0.5,
        inStock: true,
        location: "Tirana",
        market: "Komiteti",
        marketSlug: "komiteti",
    },
    {
        id: 8,
        name: "Colonial Cocktail",
        price: 1000,
        imageUrl: "/images/Colonial.jpeg",
        category: "bars",
        description: "Trendy bar with cocktails",
        retailer: "Colonial",
        distance: 1.2,
        inStock: true,
        location: "Tirana",
        market: "Colonial",
        marketSlug: "colonial",
    },
    {
        id: 9,
        name: "Mugo Signature",
        price: 850,
        imageUrl: "/images/Mugo.jpeg",
        category: "bars",
        description: "Modern bar with live music",
        retailer: "Mugo",
        distance: 1.6,
        inStock: true,
        location: "Tirana",
        market: "Mugo",
        marketSlug: "mugo",
    },
    {
        id: 10,
        name: "SkyTower View",
        price: 900,
        imageUrl: "/images/SkyTower.jpeg",
        category: "bars",
        description: "Rooftop cocktails with a view",
        retailer: "SkyTower",
        distance: 0.8,
        inStock: true,
        location: "Tirana",
        market: "SkyTower",
        marketSlug: "skytower",
    },
    {
        id: 11,
        name: "Fanta Exotic 500ml",
        price: 135,
        imageUrl: "/images/fanta-exotic.jpg",
        category: "drinks",
        retailer: "Big Market",
        inStock: true,
        location: "Tirana",
        market: "Big Market",
        marketSlug: "big-market",
    },
    {
        id: 12,
        name: "Fanta Exotic 500ml",
        price: 150,
        imageUrl: "/images/fanta-exotic.jpg",
        category: "drinks",
        retailer: "Spar",
        inStock: true,
        location: "Tirana",
        market: "Spar",
        marketSlug: "spar",
    },
    {
        id: 13,
        name: "Fanta Exotic 500ml",
        price: 120,
        imageUrl: "/images/fanta-exotic.jpg",
        category: "drinks",
        retailer: "Conad",
        inStock: true,
        location: "Tirana",
        market: "Conad",
        marketSlug: "conad",
    },
    {
        id: 14,
        name: "Fanta Exotic 500ml",
        price: 140,
        imageUrl: "/images/fanta-exotic.jpg",
        category: "drinks",
        retailer: "AlbMarket",
        inStock: true,
        location: "Tirana",
        market: "AlbMarket",
        marketSlug: "albmarket",
    },
    {
        id: 15,
        name: "Fanta Exotic 500ml",
        price: 130,
        imageUrl: "/images/fanta-exotic.jpg",
        category: "drinks",
        retailer: "ProNatyra",
        inStock: true,
        location: "Tirana",
        market: "ProNatyra",
        marketSlug: "pronatyra",
    },
    {
        id: 16,
        name: "Fanta Exotic 500ml - Big Market",
        price: 135,
        imageUrl: "/images/fanta-exotic.jpg",
        category: "featured",
        description: "Popular soft drink from the groceries selection",
        retailer: "Big Market",
        inStock: true,
        location: "Tirana",
        market: "Big Market",
        marketSlug: "big-market",
    },
    {
        id: 17,
        name: "Fanta Exotic 500ml - Spar",
        price: 150,
        imageUrl: "/images/fanta-exotic.jpg",
        category: "featured",
        description: "Groceries item spotlight from Spar",
        retailer: "Spar",
        inStock: true,
        location: "Tirana",
        market: "Spar",
        marketSlug: "spar",
    },
    {
        id: 18,
        name: "Fanta Exotic 500ml - Conad",
        price: 120,
        imageUrl: "/images/fanta-exotic.jpg",
        category: "featured",
        description: "Groceries item spotlight from Conad",
        retailer: "Conad",
        inStock: true,
        location: "Tirana",
        market: "Conad",
        marketSlug: "conad",
    },
    {
        id: 19,
        name: "Fresh Apple",
        price: 5.99,
        imageUrl: "/placeholder.jpg",
        category: "groceries",
        description: "Crisp apples from local farms",
        retailer: "Big Market",
        inStock: true,
        location: "Tirana",
        market: "Big Market",
        marketSlug: "big-market",
    },
    {
        id: 20,
        name: "Sweet Banana",
        price: 3.99,
        imageUrl: "/placeholder.jpg",
        category: "groceries",
        description: "Fresh bananas imported weekly",
        retailer: "Spar",
        inStock: true,
        location: "Durres",
        market: "Spar",
        marketSlug: "spar",
    },
    {
        id: 21,
        name: "Craft Beer",
        price: 2.99,
        imageUrl: "/placeholder.jpg",
        category: "bars",
        description: "Local craft beer bottle",
        retailer: "Local Bar",
        inStock: true,
        location: "Tirana",
    },
    {
        id: 22,
        name: "Margherita Pizza",
        price: 12.99,
        imageUrl: "/placeholder.jpg",
        category: "restaurants",
        description: "Fresh basil and mozzarella",
        retailer: "La Pizza",
        inStock: true,
        location: "Tirana",
    },
    {
        id: 23,
        name: "Classic Burger",
        price: 9.99,
        imageUrl: "/placeholder.jpg",
        category: "restaurants",
        description: "Beef patty with cheddar cheese",
        retailer: "Burger House",
        inStock: true,
        location: "Durres",
    },
]
